### ISSUE TITLE
hola-chaining route not working when testing locally

### ISSUE THREAD

**Issue by rsriniva** [jimrigsbee/hello#3]
When testing locally, hola-chaining request always responds with fallback because the call to aloha service fails. 

I guess we are missing some external config. when testing locally hola always looks for aloha:8080 which obviously does not work and no route to host error is seen in the logs.

When deployed on OpenShift, hola route does not work (sepoarate defect opened on this issue)

**Comment by rtaniguchi** [comment]
@rsriniva This behavior is expected because you must run both the hola and aloha apps on the same machine. If that is not true, the fallback is executed. The discussion about the pattern was recorded: https://bluejeans.com/s/BiWNO

Initially, the proxy points to aloha:8080 (which does not exists, unless you have a machine with the same hostname). You may change the configuration using the microprofile-config.properties from the hola project to point to a place where your service is running.

Also, this behavior is tested using the /hola/src/test/java/com/redhat/training/msa/hola/rest/HolaResourceNoFallbackTest.java test. That test starts a server and runs a stub version of the aloha app.
